image: yupix/intsl

stages:
  - local_check
  - package_check
  # - server_create

local_check:
    tags:
        - linux
        - archlinux
        - docker
    stage: local_check
    script:
        - export PATH="$(pwd)/usr/bin:$PATH"
        - intsl -V

package_check:
    tags:
        - linux
        - archlinux
        - docker
    stage: package_check
    script:
        - intsl -V