#!/usr/bin/env bash
#TODO: 最大メモリが最初を下回らないように作る (2020/4/17)
#解説系
description1="サーバーのプロセス名を変更"
description2="JARファイルの名前を変更"
description3="最大メモリを変更"
description4="最小メモリを変更"

#サーバーのオプション系
use_option1="screen_name"
use_option2="file_server_file"
use_option3="mem_max"
use_option4="mem_min"

#sedコマンド
. $server_dir/setting.txt

for a in $(seq 1 4); do
    if [[ ${a} = ${change_setting_number} ]]; then
        option="use_option"
        eval $option="\$use_option$a"
        #echo "eval $use_option="\$option${a}""
        #use_sed="sed_command"
        #eval $use_sed="\$${server_name}_${use_option}"
        use_description="description"
        eval ${use_description}="\$description${change_setting_number}"
        use_sed="${server_name}_${use_option}"
        use_sed2="sed_comman"
        eval $use_sed2="\$${server_name}_${use_option}"
        break
    fi
done
echo "$description"
if [ ${change_setting_number} = 3 -o ${change_setting_number} = 4 ]; then
    while :; do
        echo "使用する数値を入力してください。(単位等も除く)"
        read -p ">" input_data
        if [[ "${input_data}" =~ ^[0-9]+$ ]]; then
            echo "単位を選択してください (GB / MB)"
            while :; do
                read -p ">" input_unit_data
                overwrite_unit_data=$(echo "${input_unit_data,,}" | grep -o -e "g" -e "m")
                case ${overwrite_unit_data} in
                [gG] | [mM])
                    use_unit="${overwrite_unit_data,,}"
                    break
                    ;;
                *)
                    echo "GBまたはMBを選択してください"
                    ;;
                esac
            done
            echo "最終確認: ${input_data}${use_unit^}Bでよろしいですか?"
            read -p ">" final_check_data
            case ${final_check_data} in
            [yY] | [yY][eE][sS])
                spinner_progress_status="設定を更新中"
                SPINNER
                break
                ;;
            [nN] | [oO])
                echo "再設定を行います"
                ;;
            *)
                echo "(Y)es または (N)oを入力してください。"
            ;;
            esac
        else
            echo "数字を入力してください。"
        fi
    done
else
    echo "使用する名前を入力してください"
    read -p ">" input_data
fi

sed -i -e 's/'$use_sed'="'${sed_comman}'"/'$use_sed'="'${input_data}${use_unit}'"/' $server_dir/setting.txt
