#!/usr/bin/env bash
SERVER_LIST() {
    case $input_server_name in
    #STARTSERVERLIST





    #ENDSERVERLIST
    *)
        #不正なキー入力
        echo "存在しないサーバーです"
        exit 1
        ;;
    esac
}

server_list_get() {
    for a in $(seq ${number_of_server}); do
        purpose="get"
        input_server_name="${a}"
        SERVER_LIST
        . ${mc_settings_file_locations}/setting.txt
        if [[ ${server_name} = ${input_server_name} ]]; then
            covering_check="true"
            break
        fi
    done
}

if [[ ${purpose} = remove ]]; then
    if [[ -z $input_server_name ]]; then
        echo "${word}を入力してください"
        read -r -p ">" input_server_name
    fi
    SERVER_LIST
    get_ext_manager_start_line=$(grep -nw ${input_server_name,,}START ${VAR_LIB_FILE_LOCATIONS}server_list | cut -d'\:' -f1)
    get_ext_manager_exit_line=$(grep -nw ${input_server_name,,}EXIT ${VAR_LIB_FILE_LOCATIONS}server_list | cut -d'\:' -f1)
    sed -i -e ''${get_ext_manager_start_line}','${get_ext_manager_exit_line}'d' ${VAR_LIB_FILE_LOCATIONS}server_list
    new_server_add_line=$((server_add_line - 6))
    sed -i -e 's/server_add_line="'${server_add_line}'"/server_add_line="'${new_server_add_line}'"/' ${SETTING_FILE_LOCATIONS}settings
    #サーバー数増減
    new_number_of_server=$((number_of_server - 1))
    sed -i -e 's/number_of_server="'${number_of_server}'"/number_of_server="'${new_number_of_server}'"/' ${SETTING_FILE_LOCATIONS}settings

    echo "サーバーリストから正常に削除しました"
    echo "操作は正常に終了しました..."
    if [[ ${auto_remove} = "true" ]]; then
        echo -e "${ECHO_GREEN_BOLD_COLOR}==> Removefile${ECHO_COLOR_EXIT}"
        echo -e "${ECHO_BLUE_BOLD_COLOR}  ->${ECHO_COLOR_EXIT} ${ECHO_WHITE_BOLD_COLOR}Running Removing File${ECHO_COLOR_EXIT}"
        SERVER_LIST
        . ${mc_settings_file_locations}/setting.txt
        rm -rf ${mc_settings_file_locations}
        if [[ ! -e ${mc_settings_file_locations} ]]; then
            echo -e "${ECHO_GREEN_BOLD_COLOR}==> Successful on Remove file${ECHO_COLOR_EXIT}"
        fi
    else
        echo "サーバーディレクトリは ${mc_settings_file_locations} です。"
        echo "手動削除をお願いします"
    fi
    unset input_server_name
elif [[ ${purpose} = get ]]; then
    server_list_get
elif [[ ${purpose} = list ]]; then
    echo "=========================="
    for a in $(seq ${number_of_server}); do
        purpose="list"
        input_server_name="${a}"
        SERVER_LIST
        . ${mc_settings_file_locations}/setting.txt
        echo "${server_name}"
        if [[ ${mc_run_server_status} = offline ]]; then
            echo -e "┗   ${ECHO_RED_BOLD_COLOR}${mc_run_server_status}${ECHO_COLOR_EXIT}"
        else
            echo -e "┗   ${ECHO_GREEN_BOLD_COLOR}${mc_run_server_status}${ECHO_COLOR_EXIT}"
        fi
        echo "=========================="
    done
    if [[ -z $input_server_name ]]; then
        echo "サーバーが存在しません"
        exit 0
    fi

else
    if [[ -z $input_server_name ]]; then
        echo "${word}を入力してください"
        read -r -p ">" input_server_name
        SERVER_LIST
    else
        SERVER_LIST
    fi
    export mc_settings_file_locations
    ${LIB_FILE_LOCATIONS}mc_server_run/server_default_manager
fi
