#!/usr/bin/env bash
SERVER_LIST() {
    case $serverstartlist in
    #STARTSERVERLIST





    #ENDSERVERLIST
    *)
        #不正なキー入力
        echo "存在しないサーバーです"
        exit 1
        ;;
    esac
}

if [[ ${purpose} = remove ]]; then
    if [[ -z $serverstartlist ]]; then
        echo "${word}を入力してください"
        read -p ">" serverstartlist
        SERVER_LIST
    fi
    sed -i -e 's/server_add_line="'${server_add_line}'"/server_add_line="'${new_server_add_line}'"/' ${SETTING_FILE_LOCATIONS}settings
    #サーバー数増減
    new_number_of_server=$((number_of_server - 1))
    sed -i -e 's/number_of_server="'${number_of_server}'"/number_of_server="'${new_number_of_server}'"/' ${SETTING_FILE_LOCATIONS}settings

    rm -rf ${LIB_FILE_LOCATIONS}mc_server_run/${serverstartlist}
    echo "サーバーリストから正常に削除しました"
    echo "操作は正常に終了しました..."
    if [[ ${auto_remove} = "true" ]]; then
        echo -e "${ECHO_GREEN_BOLD_COLOR}==> Removefile${ECHO_COLOR_EXIT}"
        echo -e "${ECHO_BLUE_BOLD_COLOR}  ->${ECHO_COLOR_EXIT} ${ECHO_WHITE_BOLD_COLOR}Running Removing File${ECHO_COLOR_EXIT}"
        rm -rf ${mc_settings_file_locations}
        if [[ ! -e ${mc_settings_file_locations} ]]; then
            echo -e "${ECHO_GREEN_BOLD_COLOR}==> Successful on Remove file${ECHO_COLOR_EXIT}"
        fi
    else
        echo "サーバーディレクトリは ${mc_settings_file_locations} です。"
        echo "手動削除をお願いします"
    fi
    unset serverstartlist
elif [[ ${purpose} = get ]]; then
    for a in $(seq ${number_of_server}); do
        purpose="get"
        serverstartlist="${a}"
        SERVER_LIST
        . ${mc_settings_file_locations}/setting.txt
        if [[ ${server_name} = ${input_server_name} ]]; then
            covering_check="true"
            break
        fi
    done

elif [[ ${purpose} = list ]]; then
    echo "=========================="
    for a in $(seq ${number_of_server}); do
        purpose="list"
        serverstartlist="${a}"
        SERVER_LIST
        . ${mc_settings_file_locations}/setting.txt
        echo "${server_name}"
        if [[ ${mc_run_server_status} = offline ]]; then
            echo -e "┗   ${ECHO_RED_BOLD_COLOR}${mc_run_server_status}${ECHO_COLOR_EXIT}"
        else
            echo -e "┗   ${ECHO_GREEN_BOLD_COLOR}${mc_run_server_status}${ECHO_COLOR_EXIT}"
        fi
        echo "=========================="
    done
    if [[ -z $serverstartlist ]]; then
        echo "サーバーが存在しません"
        exit 0
    fi

else
    if [[ -z $serverstartlist ]]; then
        echo "${word}を入力してください"
        read -p ">" serverstartlist
        SERVER_LIST
    fi
    export mc_settings_file_locations
    ${LIB_FILE_LOCATIONS}mc_server_run/server_default_manager
fi
